# Generated by Django 5.0.4 on 2024-04-24 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complexity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('easy', models.CharField(default='Easy', max_length=6, verbose_name='Easy')),
                ('medium', models.CharField(default='Medium', max_length=8, verbose_name='Medium')),
                ('hard', models.CharField(default='Hard', max_length=4, verbose_name='Hard')),
            ],
            options={
                'verbose_name': 'Сложность',
                'verbose_name_plural': 'Сложности',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='complexity_bunch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.complexity', verbose_name='Сложность'),
        ),
    ]
