# Generated by Django 5.0.4 on 2024-04-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_complexity_task_complexity_bunch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complexity',
            name='easy',
        ),
        migrations.RemoveField(
            model_name='complexity',
            name='hard',
        ),
        migrations.RemoveField(
            model_name='complexity',
            name='medium',
        ),
        migrations.AddField(
            model_name='complexity',
            name='ComplexityTask',
            field=models.CharField(default='Easy', max_length=11, verbose_name='Easy'),
        ),
    ]
