# Generated by Django 5.0.4 on 2024-04-25 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_complexity_easy_remove_complexity_hard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatusTask', models.CharField(default='In progress', max_length=11, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.AlterField(
            model_name='complexity',
            name='ComplexityTask',
            field=models.CharField(default='Easy', max_length=11, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Описание задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='task',
            name='status_bunch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.status', verbose_name='Статус'),
        ),
    ]
