# Generated by Django 5.0.4 on 2024-04-25 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_status_alter_complexity_complexitytask_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='complexity_bunch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complexity', to='users.complexity', verbose_name='Сложность'),
        ),
    ]
