# Generated by Django 5.0.4 on 2024-04-26 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_task_complexity_bunch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complexity',
            old_name='ComplexityTask',
            new_name='complexity_task',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='StatusTask',
            new_name='status_task',
        ),
    ]
